spring:
  cloud:
    config:
      enabled: false

logging:
  level:
    root: INFO
    ru.yandex.practicum.collector: TRACE

grpc:
  server:
    port: 59091
    enableKeepAlive: true
    keepAliveWithoutCalls: true
    negotiationType: plaintext

topics:
  sensors: "telemetry.sensors.v1"
  snapshots: "telemetry.snapshots.v1"
  hubs: "telemetry.hubs.v1"

kafka-collector:
  producer:
    properties:
      bootstrap.servers: "localhost:9092"
      group.id: "telemetry-collector-producer-v1"
      key.serializer: "org.apache.kafka.common.serialization.VoidSerializer"
      value.serializer: "ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer"