spring:
  config:
    import: classpath:/application-general.yml

logging:
  level:
    root: INFO
    ru.yandex.practicum.collector: TRACE

grpc:
  server:
    # port:8080 по заданию вроде такой
    port: 8080
    enableKeepAlive: true
    keepAliveWithoutCalls: true
    negotiationType: plaintext