spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/commerce_shopping_store
    username: frosty
    password: ytsorf
    driver-class-name: org.postgresql.Driver
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=60m

management:
  endpoints:
    web:
      exposure:
        include: health, mappings, httptrace, caches, threaddump

logging:
  level:
    root: INFO
    ru.yandex.practicum.shopping.store: TRACE